src/Entity/Activity.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActivityRepository")
 */
class Activity
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $max_people;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(?string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getMaxPeople(): ?string
    {
        return $this->max_people;
    }

    public function setMaxPeople(?string $max_people): self
    {
        $this->max_people = $max_people;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ActivityType.php
<?php

namespace App\Form;

use App\Entity\Activity;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('file_name')
            ->add('max_people')
            ->add('description')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Form\ActivityType;
use App\Repository\ActivityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/activity")
 */
class ActivityController extends AbstractController
{
    /**
     * @Route("/", name="activity_index", methods={"GET"})
     */
    public function index(ActivityRepository $activityRepository): Response
    {
        return $this->render('activity/index.html.twig', [
            'activities' => $activityRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="activity_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($activity);
            $entityManager->flush();

            return $this->redirectToRoute('activity_index');
        }

        return $this->render('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="activity_show", methods={"GET"})
     */
    public function show(Activity $activity): Response
    {
        return $this->render('activity/show.html.twig', [
            'activity' => $activity,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="activity_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Activity $activity): Response
    {
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('activity_index', [
                'id' => $activity->getId(),
            ]);
        }

        return $this->render('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="activity_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Activity $activity): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activity->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($activity);
            $entityManager->flush();
        }

        return $this->redirectToRoute('activity_index');
    }
}

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');" class="d-flex justify-content-center">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/activity/_form.html.twig
<div class="container">
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <br>
        <div class="d-flex justify-content-center">
            <button class="btn btn-success">{{ button_label|default('Save') }}</button>
        </div>
        <br>
    {{ form_end(form) }}
</div>

templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activity{% endblock %}

{% block body %}
    <h1 class="d-flex justify-content-center site_title">Edit Activity</h1>

    {{ include('activity/_form.html.twig', {'button_label': 'Update'}) }}
    
    <div class="d-flex justify-content-center">
        <a href="{{ path('activity_index') }}" class="btn btn-primary">back to list</a>
    </div></br>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity index{% endblock %}

{% block body %}
    <h1 class="d-flex justify-content-center site_title">Activity index</h1>

    <div class="table-responsive">
        <table class="table container table-striped table-bordered table-hover animated fadeIn" style="max-width:90%">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">File_name</th>
                    <th scope="col">Max_people</th>
                    <th scope="col">Description</th>
                    <th scope="col" style="min-width:150px;">actions</th>
                </tr>
            </thead>
            <tbody>
            {% for activity in activities %}
                <tr>
                    <td>{{ activity.id }}</td>
                    <td>{{ activity.name }}</td>
                    <td>{{ activity.fileName }}</td>
                    <td>{{ activity.maxPeople }}</td>
                    <td>{{ activity.description }}</td>
                    <td>
                        <a href="{{ path('activity_show', {'id': activity.id}) }}" class="btn btn-success">show</a>
                        <a href="{{ path('activity_edit', {'id': activity.id}) }}" class="btn btn-warning">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    
    <a href="{{ path('activity_new') }}" class="d-flex justify-content-center">
        <strong class="btn btn-primary animated pulse slow">Create new</strong>
    </a>
{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activity{% endblock %}

{% block body %}
    <h1 class="d-flex justify-content-center site_title">Create new Activity</h1>
    <br><br>

    {{ include('activity/_form.html.twig') }}

    <a href="{{ path('activity_index') }}" class="d-flex justify-content-center">
        <strong class="btn btn-primary"> back to list</strong>
    </a>
{% endblock %}

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity{% endblock %}

{% block body %}
    <h1 class="d-flex justify-content-center site_title">Activity</h1>

    <table class="table container table-striped table-bordered table-hover animated fadeIn" style="max-width:90%">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ activity.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ activity.name }}</td>
            </tr>
            <tr>
                <th>File_name</th>
                <td>{{ activity.fileName }}</td>
            </tr>
            <tr>
                <th>Max_people</th>
                <td>{{ activity.maxPeople }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ activity.description }}</td>
            </tr>
        </tbody>
    </table>
    
    <div class="d-flex justify-content-center">
        <a href="{{ path('activity_index') }}" class="btn btn-primary">back to list</a>
        <div class="col-1"></div>
        <a href="{{ path('activity_edit', {'id': activity.id}) }}" class="btn btn-warning">edit</a>
        <div class="col-1"></div>
        {{ include('activity/_delete_form.html.twig') }}
    </div>
{% endblock %}